name: Theo Grace Music Lessons
favicon: null
layout_spectrum: 0.74958
typography_spectrum: 0.32232331903651357
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#18162c'
    - '#f4d094'
    - '#003ab8'
    - '#1e8ae5'
    - '#fe7b00'
  brandStrength: 1
  lightness: 0.5625
  saturation: 1
  rhythmicContrast: 0
purpose: []
