name: Theo Grace Music Lessons
favicon: null
layout_spectrum: 0.50918
typography_spectrum: 0.32232331903651357
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f0a561'
    - '#2a3e32'
    - '#000100'
    - '#442500'
    - '#7a5009'
  brandStrength: 1
  lightness: 0.5625
  saturation: 1
  rhythmicContrast: 0
purpose: []
