name: Theo Grace Music Lessons
favicon: null
layout_spectrum: 0.74958
typography_spectrum: 0.32232331903651357
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefef6'
    - '#455974'
    - '#e7be9e'
    - '#182341'
    - '#915d24'
  brandStrength: 1
  lightness: 0.5625
  saturation: 1
  rhythmicContrast: 0
purpose: []
