name: Theo Grace Music Lessons
favicon: null
layout_spectrum: 0.6944793870206922
typography_spectrum: 0.32232331903651357
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.7898767101578414
  lightness: 0.40658758021891117
  saturation: 0.7606153432279825
  rhythmicContrast: 0.6459460265468806
purpose: []
